config/routes.rb
Rails.application.routes.draw do
  root "others/pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions", confirmations: "users/confirmations", passwords: "users/passwords", unlocks: "users/unlocks" }

  resources :portfolios, only: [ :index, :show ] do
    resources :ideas, only: [ :index, :show ]
    resources :projects, only: [ :index, :show ]
  end

  resources :ideas, only: [ :index, :show ]
  resources :projects, only: [ :index, :show ]

  namespace :dashboard do
    resource :portfolio, only: [ :show, :edit, :update ] do
      resources :ideas, except: [ :destroy ]
      resources :projects, except: [ :destroy ]
    end

    resources :ideas, only: [ :destroy ]
    resources :projects, only: [ :destroy ]
  end

  resources :reactions, only: [ :create, :update, :destroy ]

  namespace :admin do
    resources :users
    resources :portfolios
    resources :ideas
    resources :projects
  end
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  belongs_to :user

  has_many :ideas, dependent: :destroy
  has_many :projects, dependent: :destroy
  has_one_attached :qr_code
  has_one_attached :avatar

  after_create :generate_my_qr_code

  BASE_URL = "https://www.olenxplatforms.com/portfolios"

  def self.ransackable_attributes(_auth_object = nil)
    %w[company_name description]
  end

  def self.ransackable_associations(_auth_object = nil)
    []
  end

  def generate_my_qr_code
    if self.qr_code.attached?
      self.qr_code.purge
    end
    qr = RQRCode::QRCode.new("#{BASE_URL}/#{self.id}")
    png = qr.as_png(
      bit_depth: 1,
      border_modules: 0,
      color_mode: ChunkyPNG::COLOR_GRAYSCALE,
      color: "black",
      file: nil,
      fill: "white",
      module_px_size: 6,
      resize_exactly_to: false,
      resize_gte_to: false,
      size: 120
    )
    # attach the png to the portfolio as qr_code by cloudinary
    self.qr_code.attach(
      io: StringIO.new(png.to_s),
      filename: "qr_code_portfolio_#{self.id}.png",
      content_type: "image/png",
      identify: false,
      metadata: {
        title: "QR code for portfolio #{self.id}",
        alt: "QR code for portfolio #{self.id}"
      }
    )
  end
end

app/controllers/admin/portfolios_controller.rb
class Admin::PortfoliosController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only

  def index
    @portfolios = Portfolio.all
  end

  def show
    @portfolio = Portfolio.includes(:ideas, :projects).with_attached_avatar.with_attached_qr_code.find(params[:id])
  end

  def edit
    @portfolio = Portfolio.find(params[:id])
  end

  def update
    @portfolio = Portfolio.find(params[:id])
    if @portfolio.update(portfolio_params)
      redirect_to admin_portfolio_path(@portfolio), notice: "Le portfolio a bien été mis à jour"
    else
      render :edit
    end
  end

  def destroy
    @portfolio = Portfolio.find(params[:id])
    if @portfolio.destroy
      redirect_to admin_portfolios_path, notice: "Le portfolio a bien été supprimé"
    else
      redirect_to admin_portfolios_path, alert: "Impossible de supprimer le portfolio"
    end
  end

  private

  def portfolio_params
    params.require(:portfolio).permit(:name, :description, :avatar)
  end

  def admin_only
    redirect_to root_path, alert: "Vous n'avez pas les droits nécessaires" unless current_user.admin?
  end
end

app/controllers/dashboard/ideas_controller.rb
class Dashboard::IdeasController < ApplicationController
  before_action :authenticate_user!
  before_action :set_portfolio, only: %i[index show new create edit update destroy]


  def index
    @ideas = @portfolio.ideas.with_attached_avatar.order(updated_at: :desc)
  end

  def show
    @idea = @portfolio.ideas.with_attached_avatar.find(params[:id])
    @reaction = current_user.reactions.find_by(idea: @idea) if user_signed_in?
  end

  def new
    @idea = @portfolio.ideas.new
  end

  def create
    @idea = @portfolio.ideas.new(idea_params)
    if @idea.save
      redirect_to dashboard_portfolio_idea_path(@idea), notice: "L'idée a bien été créée"
    else
      render :new
    end
  end

  def edit
    @idea = @portfolio.ideas.find(params[:id])
  end

  def update
    @idea = @portfolio.ideas.find(params[:id])
    if @idea.update(idea_params)
      redirect_to dashboard_portfolio_idea_path(@idea), notice: "L'idée de projet a bien été mise à jour"
    else
      render :edit
    end
  end

  def destroy
    @idea = Idea.find(params[:id])
    if @idea.destroy
      redirect_to dashboard_portfolio_ideas_path(@portfolio), notice: "L'idée de projet a bien été supprimée"
    else
      render :edit, alert: "Impossible de supprimer l'idée"
    end
  end

  private

  def idea_params
    params.require(:idea).permit(:title, :description, :avatar)
  end

  def set_portfolio
    @portfolio = current_user.portfolio
  end
end

app/controllers/dashboard/portfolios_controller.rb
class Dashboard::PortfoliosController < ApplicationController
  before_action :authenticate_user!

  def show
    @portfolio = Portfolio.includes(:ideas, :projects)
    .with_attached_avatar
    .with_attached_qr_code
    .find_by!(user: current_user)
  end

  def edit
    @portfolio = current_user.portfolio
  end

  def update
    @portfolio = current_user.portfolio
    if @portfolio.update(portfolio_params)
      redirect_to dashboard_portfolio_path, notice: "Le portfolio a bien été mis à jour"
    else
      render :edit
    end
  end

  private

  def portfolio_params
    params.require(:portfolio).permit(:company_name, :description, :avatar)
  end
end

app/controllers/dashboard/projects_controller.rb
class Dashboard::ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_portfolio, only: %i[index show new create edit update]

  def index
    @projects = @portfolio.projects.with_attached_avatar.order(updated_at: :desc)
  end

  def show
    @project = @portfolio.projects.with_attached_avatar.find(params[:id])
  end

  def new
    @project = @portfolio.projects.new
  end

  def create
    @project = @portfolio.projects.new(project_params)
    if @project.save
      redirect_to dashboard_portfolio_project_path(@project), notice: "L'idée a bien été créée"
    else
      render :new
    end
  end

  def edit
    @project = @portfolio.projects.find(params[:id])
  end

  def update
    @project = @portfolio.projects.find(params[:id])
    if @project.update(project_params)
      redirect_to dashboard_portfolio_project_path(@project), notice: "L'idée de projet a bien été mise à jour"
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    if @project.destroy
      redirect_to dashboard_portfolio_path, notice: "L'idée de projet a bien été supprimée"
    else
      redirect_to dashboard_portfolio_project_path(@project), alert: "Impossible de supprimer l'idée"
    end
  end

  private

  def project_params
    params.require(:project).permit(:title, :description, :avatar)
  end

  def set_portfolio
    @portfolio = current_user.portfolio
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]

  def index
    params.permit(q: {})
    @q = Portfolio.ransack(params[:q])
    @portfolios = @q.result(distinct: true).with_attached_avatar
  end

  def show
    @portfolio = Portfolio.includes(:ideas, :projects).with_attached_avatar.with_attached_qr_code.find(params[:id])
  end
end

app/helpers/admin/portfolios_helper.rb
module Admin::PortfoliosHelper
end

app/helpers/dashboard/ideas_helper.rb
module Dashboard::IdeasHelper
end

app/helpers/dashboard/portfolios_helper.rb
module Dashboard::PortfoliosHelper
end

app/helpers/dashboard/projects_helper.rb
module Dashboard::ProjectsHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/dashboard/portfolios/edit.html.erb
<main class="p-4 flex flex-col gap-8">
  <h1 class="uppercase font-bold leading-[1.2] text-[2.25rem]">Modifier mon Portfolio</h1>
  <%# <p>Find me in app/views/dashboard/portfolios/edit.html.erb</p> %>
  <%= form_with model: @portfolio, url: dashboard_portfolio_path, method: :patch, html: { class: 'flex flex-col gap-4' } do |form| %>
    <!-- Titre -->
    <div class="flex flex-col gap-2">
      <%= form.label :company_name, "Nom de l'entreprise", class:'font-medium' %>
      <%= form.text_field :company_name, class: "p-2 border border-[var(--border-input)] rounded-[5px] w-full focus:outline-none focus:ring-[var(--txt-hover)] focus:ring-1"%>
      <% if @portfolio.errors[:company_name].any? %>
        <p class="text-red-500 text-sm mt-1"><%= @portfolio.errors[:company_name].join(", ") %></p>
      <% end %>
    </div>
    <!-- Description -->
    <div class="flex flex-col gap-2">
      <%= form.label :description, "Description", class:'font-medium' %>
      <%= form.text_area :description, class: "p-2 border border-[var(--border-input)] rounded-[5px] w-full focus:outline-none focus:ring-[var(--txt-hover)] focus:ring-1 resize-none" %>
      <% if @portfolio.errors[:description].any? %>
        <p class="text-red-500 text-sm mt-1"><%= @portfolio.errors[:description].join(", ") %></p>
      <% end %>
    </div>
    <!-- Avatar -->
    <div class="flex flex-col gap-2">
      <%= form.label :avatar,"Photo de profil", class:'font-medium'  %>
      <%= form.file_field :avatar, class: "p-2 border border-[var(--border-input)] rounded-[5px] w-full focus:outline-none focus:ring-[var(--txt-hover)] focus:ring-1", placeholder: 'Parcourir mes images' %>
      <% if @portfolio.errors[:avatar].any? %>
        <p class="text-red-500 text-sm mt-1"><%= @portfolio.errors[:avatar].join(", ") %></p>
      <% end %>
    </div>
    <!-- Bouton de soumission -->
    <div class="flex flex-col gap-2">
      <%= form.submit "Enregistrer", class: "w-max px-6 py-3 rounded-[24px] border border-black bg-white text-black transition-all duration-400 ease-in-out hover:bg-[var(--txt-hover)] hover:text-white hover:border-[var(--txt-hover)] cursor-pointer" %>
    </div>
  <% end %>
</main>

app/views/dashboard/portfolios/show.html.erb
<main class="max-w-[97dvw] min-h-screen mx-auto">
  <!-- Informations du portfolio -->
  <section class="grid grid-cols-[80%_20%] md:grid-cols-[90%_10%] items-center border-b-2 border-[var(--tag-color)] py-[50px] px-[20px]">
    <div class="flex gap-4 items-center">
      <%= link_to portfolio_path(@portfolio) do %>
        <% if @portfolio.avatar.attached? %>
          <%= cl_image_tag @portfolio.avatar.key, width: 50, height: 50, class: "rounded-full aspect-[1/1]" %>
        <% end %>
      <% end %>
      <div class="">
        <h1 class="font-semibold text-2xl ">
          <%= @portfolio.company_name %>
        </h1>
        <p class="text-[var(--tag-color)]">
          <%= @portfolio.description %>
        </p>
      </div>
    </div>
    <div class="flex gap-4">
      <%= link_to edit_dashboard_portfolio_path do %>
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 512 512" fill="white">
          <path d="M362.7 19.3L314.3 67.7 444.3 197.7l48.4-48.4c25-25 25-65.5 0-90.5L453.3 19.3c-25-25-65.5-25-90.5 0zm-71 71L58.6 323.5c-10.4 10.4-18 23.3-22.2 37.4L1 481.2C-1.5 489.7 .8 498.8 7 505s15.3 8.5 23.7 6.1l120.3-35.4c14.1-4.2 27-11.8 37.4-22.2L421.7 220.3 291.7 90.3z"/>
        </svg>
      <% end %>
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 448 512" fill="white"><!--!Font Awesome Free 6.7.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2025 Fonticons, Inc.--><path d="M0 80C0 53.5 21.5 32 48 32l96 0c26.5 0 48 21.5 48 48l0 96c0 26.5-21.5 48-48 48l-96 0c-26.5 0-48-21.5-48-48L0 80zM64 96l0 64 64 0 0-64L64 96zM0 336c0-26.5 21.5-48 48-48l96 0c26.5 0 48 21.5 48 48l0 96c0 26.5-21.5 48-48 48l-96 0c-26.5 0-48-21.5-48-48l0-96zm64 16l0 64 64 0 0-64-64 0zM304 32l96 0c26.5 0 48 21.5 48 48l0 96c0 26.5-21.5 48-48 48l-96 0c-26.5 0-48-21.5-48-48l0-96c0-26.5 21.5-48 48-48zm80 64l-64 0 0 64 64 0 0-64zM256 304c0-8.8 7.2-16 16-16l64 0c8.8 0 16 7.2 16 16s7.2 16 16 16l32 0c8.8 0 16-7.2 16-16s7.2-16 16-16s16 7.2 16 16l0 96c0 8.8-7.2 16-16 16l-64 0c-8.8 0-16-7.2-16-16s-7.2-16-16-16s-16 7.2-16 16l0 64c0 8.8-7.2 16-16 16l-32 0c-8.8 0-16-7.2-16-16l0-160zM368 480a16 16 0 1 1 0-32 16 16 0 1 1 0 32zm64 0a16 16 0 1 1 0-32 16 16 0 1 1 0 32z"/></svg>
    </div>
    <!-- QR Code et Avatar -->
  </section>
  <!-- Section Réalisations -->
  <section class="mt-8">
    <h2 class="font-semibold text-2xl mb-4">
      Mes réalisations
    </h2>
    <% if @portfolio.projects.any? %>
      <ul class="max-w-[97dvw] mx-auto grid grid-cols-1 gap-[3em] rounded-b-[20px] md:grid-cols-3 md:p-12">
        <% @portfolio.projects.each do |project| %>
          <%= render 'dashboard/projects/components/dashboard_project_card', project: project %>
        </li>
      <% end %>
      <li>
        <%= link_to new_dashboard_portfolio_project_path do%>
          <div class="overflow-hidden rounded-[24px] mb-4 flex flex-col h-[300px] w-full relative items-center justify-center transition-all duration-400 ease-in-out
    bg-white/5 backdrop-blur-lg border border-white/20 shadow-lg cursor-pointer ">
            <h3 class="text-2xl uppercase font-semibold hover:scale-110 flex flex-col gap-4 items-center">
              Ajoutez un projet
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="32px" height="32px" fill="white"><!--!Font Awesome Free 6.7.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2025 Fonticons, Inc.--><path d="M256 512A256 256 0 1 0 256 0a256 256 0 1 0 0 512zM232 344l0-64-64 0c-13.3 0-24-10.7-24-24s10.7-24 24-24l64 0 0-64c0-13.3 10.7-24 24-24s24 10.7 24 24l0 64 64 0c13.3 0 24 10.7 24 24s-10.7 24-24 24l-64 0 0 64c0 13.3-10.7 24-24 24s-24-10.7-24-24z"/></svg>
            </h3>
          </div>
        <% end %>
      </li>
    </ul>
  <% else %>
    <p class="text-[var(--tag-color)]">Vous n'avez pas encore inséré vos réalisations.</p>
  <% end %>
</section>
<!-- Section Idées de projets -->
<section class="mt-8">
  <h2 class="font-semibold text-2xl mb-4">
    Mes idées
  </h2>
  <% if @portfolio.ideas.any? %>
    <ul class="max-w-[97dvw] mx-auto grid grid-cols-1 gap-[3em] rounded-b-[20px] md:grid-cols-3 md:p-12">
      <% @portfolio.ideas.each do |idea| %>
        <%= render 'dashboard/ideas/components/dashboard_idea_card', idea: idea %>
      <% end %>
      <li>
        <%= link_to new_dashboard_portfolio_idea_path do %>
          <div class="overflow-hidden rounded-[24px] mb-4 flex flex-col h-[300px] w-full relative items-center justify-center transition-all duration-400 ease-in-out
    bg-white/5 backdrop-blur-lg border border-white/20 shadow-lg cursor-pointer">
            <h3 class="text-2xl uppercase font-semibold hover:scale-110 flex flex-col gap-4 items-center">
              Ajoutez une idée
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="32px" height="32px" fill="white"><!--!Font Awesome Free 6.7.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2025 Fonticons, Inc.--><path d="M256 512A256 256 0 1 0 256 0a256 256 0 1 0 0 512zM232 344l0-64-64 0c-13.3 0-24-10.7-24-24s10.7-24 24-24l64 0 0-64c0-13.3 10.7-24 24-24s24 10.7 24 24l0 64 64 0c13.3 0 24 10.7 24 24s-10.7 24-24 24l-64 0 0 64c0 13.3-10.7 24-24 24s-24-10.7-24-24z"/></svg>
            </h3>
          </div>
        <% end %>
      </li>
    </ul>
  <% else %>
    <p class="text-center">
      Vous n'avez pas encore d'idées de projet.
    </p>
    <div class="text-center my-8">
      <%= link_to 'Proposer ma 1ère idée', new_dashboard_portfolio_idea_path, class: "bg-white border-white border text-black hover:bg-black hover:text-white py-2 px-4 rounded-2xl transition hover:duration-150" %>
    </div>
  <% end %>
</section>
</main>
<%# link_to 'Retour', root_path %>
<%# <h2>
  <%# link_to 'Modifier Mon Portfolio', edit_dashboard_portfolio_path %>
</h2>
<%# <h2>
  <%# link_to 'Ajouter un Projet', new_dashboard_portfolio_project_path %>
</h2>
<h2>
  <%# link_to 'Ajouter une Idée de Projet', new_dashboard_portfolio_idea_path %>
</h2>